
language: ruby
rvm:
- 2.4.2
install: gem install bundler && gem install jekyll -v 3.6.2 && gem install s3_website && gem install jekyll-paginate && gem install rake && gem list
script: bundle exec jekyll build
after_success: s3_website push