title:             Matt Dalesio
email:             your-email@example.com
description:       Data Engineer
author:            Matt Dalesio
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  mddalesio
github_username:   dalmat36
facebook_username: 
linkedin_username: matt-dalesio-9350a042

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
